### PR TITLE
fix(project): #1435 fixed view project when guest login

### LINKED ISSUE #1435: Bug - can not view public project if not logged in
From the homepage, if I am not logged in, I can not view the public projects, this is a bug. I should be able to view a public project as a guest

### PR DESCRIPTION
**Pull request by webkhushboo**
closes #1435 

### Notes

A summary of what was achieved in this PR

- [ ] API: Added cloud function for updating project views
- [ ] UI: Fixed view project bug when guest login

### CODE REVIEW

File: functions/src/project/project.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+import { FirebaseAdmin } from '../client/firebase-admin';
+
+export interface ProjectInput {
+  projectUid: string
+}
+
+export const updateViews: any = async (projectUid: string): Promise<void> => {
+
+  // Update views of the project
+  await FirebaseAdmin
```
Comment (eddiejaoude) [inline functions/src/project/project.ts]: needs a `return` without the `await` for the `promise<void>`

Comment (eddiejaoude) [reply functions/src/project/project.ts]: I can add this now

File: web/src/app/core/resolvers/view-project.resolver.ts [hunk 2]
```diff
@@ -13,18 +16,20 @@ import { IProject, ProjectModel } from '@shared/models/index.model';
...
     private router: Router
   ) { }
 
   resolve(route: ActivatedRouteSnapshot): Observable<IProject> {
+    const callable: any = this.fns.httpsCallable('updateProjectViews');
     return this.projectService.findOneById(route.params.projectUid)
       .pipe(
         take(1),
-        switchMap((project: ProjectModel) => this.projectService.incrementView(project)),
+        tap(() => callable({ projectUid: route.params.projectUid })),
```
Comment (eddiejaoude) [inline web/src/app/core/resolvers/view-project.resolver.ts]: The previous service method `incrementView` is no longer needed as it has been moved to the cloud function.

Comment (eddiejaoude) [reply web/src/app/core/resolvers/view-project.resolver.ts]: I will remove this and push it up

**Comment by eddiejaoude** [comment]
Before and after my changes there is an error. I didn't get a chance to look into it.

Screenshot 2019-08-27 22 01 04

**Comment by eddiejaoude** [comment]
I fixed the permission issue as guest when viewing the project dashboard
