### PR TITLE
fix(projects): #1597 fixed the project dashboard data not coming issue

### LINKED ISSUE #1597: When new data not available, app breaks
On `dev` where it has old data (which will happen on production), the app breaks, one example is...

Screenshot 2019-11-04 18 33 28

### PR DESCRIPTION
**Pull request by webkhushboo**
closes #1597 

### Notes

A summary of what was achieved in this PR

- [ ] Fixed the "When new data not available, app breaks"

### CODE REVIEW

File: web/src/app/projects/view/view.component.ts [hunk 1]
```diff
@@ -153,7 +153,7 @@ export class ViewProjectComponent implements OnInit, OnDestroy {
    * Set the followers flag true if user uid is present in the database else set false
    */
   public isFollowing(): boolean {
-    return this.authService.profile.following.includes(this.project.uid);
+    return this.authService.profile.following && this.authService.profile.following.includes(this.project.uid);
```
Comment (eddiejaoude) [inline web/src/app/projects/view/view.component.ts:156]: I have tested it, and I think this fixes it 👍

**Review by eddiejaoude — APPROVED** [review]
