### PR TITLE
fix(project): #1427 fixed ping count issue on project page

### LINKED ISSUE #1427: 60mins monitor sometimes throws an error (I guess when url is invalid?)
Not part of this but I see an error occasionally in the logs for running the pings every 60 mins

*Note: it might be for invalid urls*

```
Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field monitors.`1`.latestPing.expectedText).
```

Screenshot 2019-08-24 08 38 28

### PR DESCRIPTION
**Pull request by webkhushboo**
closes #1427 
### Notes

A summary of what was achieved in this PR

- [ ] Fixed the ping counts issue on project page
- [ ] Fixed the invalid url issue while ping monitor

### CODE REVIEW

File: functions/src/monitor/monitor.ts [hunk 1]
```diff
@@ -38,8 +38,8 @@ export const ping: any = async (projectUid: string, monitorUid: string, type: Pi
     response = await Ping<PingResponse>(url);
   } catch (error) {
     response = {
-      statusCode: error.statusCode,
-      body: error.message,
+      statusCode: error.statusCode || 404,
+      body: error.message || 'Invalid URL',
```
Comment (eddiejaoude) [inline functions/src/monitor/monitor.ts]: 👍

File: web/src/app/shared/models/project.model.ts [hunk 2]
```diff
@@ -77,7 +77,7 @@ export class ProjectModel extends Model<IProject> implements IProject {
    */
   public getTotalPings(): number {
     let total: number = 0;
-    this.monitors.forEach((monitor: MonitorModel) => monitor.getTotalPings());
+    this.monitors.forEach((monitor: MonitorModel) => total = total + monitor.getTotalPings());
```
Comment (eddiejaoude) [inline web/src/app/shared/models/project.model.ts]: Good spot 👍 .

I will change this to use a reduce like:

```typescript
return this.monitors.reduce((accumulator, currentValue) => accumulator + currentValue.getTotalPings(), 0);
```
