### PR TITLE
chore(feat): #1192, Fixed private project should not access publicly

### LINKED ISSUE #1192: Private projects should not be accessible publicly
Server-side is protected, [firebase rules]( https://github.com/DashboardHub/PipelineDashboard/blob/firebase-mvp/firestore.rules#L20)

```gherkin
Scenario: Public projects are accessible by everyone
   Given I am not logged in
   When I access a public project
   Then I can see the project details

Scenario: Private projects are not accessible to guest or anyone other than the owner
   Given I am not logged in
   When I access a private project
   Then I am redirect to the homepage

Scenario: Private projects are only accessible by the owners
   Given I am logged in
   When I access a private project
   Then I can see the project details
```

### PR DESCRIPTION
**Pull request by webkhushboo**
closes #1192 

### Notes

- [ ] Fixed user not logged in should not access private project details using route
- [ ] Fixed user not logged in should not edit private project details using route
- [ ] Fixed user admin and logged in should be able to edit the public projects
- [ ] Fixed user not admin and logged in should not be able to edit the public projects using route

Kindly review and let me know in case of any question

### CODE REVIEW

File: web/src/app/projects/edit/edit.component.ts [hunk 1]
```diff
@@ -39,7 +44,14 @@ export class EditProjectComponent implements OnInit {
 
         this.projectSubscription = this.projectService
             .findOneById(this.uid)
-            .subscribe((project: ProjectModel) => this.projectForm.reset(project));
+            .subscribe((project: ProjectModel) => {
+                    this.project = project;
+                    this.projectForm.reset(project);
+                    // Added check for not authenticated user and private project details
+                    if ((project.type === 'private' && !this.authService.isAuthenticated) || !this.isAdmin()) {
+                        this.router.navigate(['/']);
```
Comment (eddiejaoude) [inline web/src/app/projects/edit/edit.component.ts]: Is it possible to put this check in a `guard`?

File: web/src/app/projects/view/view.component.ts [hunk 2]
```diff
@@ -28,57 +34,73 @@ export class ViewProjectComponent implements OnInit {
...
     }
 
     ngOnInit(): void {
         this.projectSubscription = this.projectService
             .findOneById(this.project.uid)
-            .subscribe((project: ProjectModel) => this.project = project);
+            .subscribe((project: ProjectModel) => {
+                this.project = project;
+                // Added check for not authenticated user and private project details
+                if (project.type === 'private' && !this.authService.isAuthenticated) {
```
Comment (eddiejaoude) [inline web/src/app/projects/view/view.component.ts]: Need to check if they are the owner also?

File: web/src/app/projects/edit/edit.component.ts (hunk 1 above)
Comment (eddiejaoude) [reply web/src/app/projects/edit/edit.component.ts]: Or resolve?

Comment (webkhushboo) [reply web/src/app/projects/edit/edit.component.ts]: I have checked if we can create guard or not . 
We are checking project is public or private based upon the uid and then we are retrieving the project details from firebase but within guard we can not retrieve the through route without navigating to it. so we have to put a check in component itself for this.

File: web/src/app/projects/view/view.component.ts (hunk 2 above)
Comment (webkhushboo) [reply web/src/app/projects/view/view.component.ts]: For viewing the public projects we need not to check if they are owner also. Any one can see the project right but in case of edit project only owner is allowed to edit the public and private projects.

File: web/src/resolvers/edit-project.resolver.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+import { ProjectService } from '../services/project.service';
+
+@Injectable({
+    providedIn: 'root'
+})
+export class EditProjectResolver implements Resolve<boolean> {
+
+    constructor(private authService: AuthenticationService,
+                private projectService: ProjectService,
+                private router: Router) {
```
Comment (eddiejaoude) [inline web/src/resolvers/edit-project.resolver.ts]: I think the formatting of this similar to above would be easier to read...

```typescript
constructor(
   private a: b,
   private c: d
) {
```

File: web/src/app/projects/view/view.component.ts [hunk 4]
```diff
@@ -28,57 +34,69 @@ export class ViewProjectComponent implements OnInit {
...
     ) {
         this.project.uid = this.route.snapshot.paramMap.get('uid');
     }
 
     ngOnInit(): void {
         this.projectSubscription = this.projectService
             .findOneById(this.project.uid)
-            .subscribe((project: ProjectModel) => this.project = project);
+            .subscribe((project: ProjectModel) => {
+                this.project = project;
```
Comment (eddiejaoude) [inline web/src/app/projects/view/view.component.ts]: This can go back to being a single line

**Comment by eddiejaoude** [comment]
Nice work. I left some small comments, but looks good 👍

File: web/src/app/projects/view/view.component.ts (hunk 4 above)
Comment (webkhushboo) [reply web/src/app/projects/view/view.component.ts]: Sure will fix. Thanks :)

File: web/src/resolvers/edit-project.resolver.ts (hunk 3 above)
Comment (webkhushboo) [reply web/src/resolvers/edit-project.resolver.ts]: Sure !!

File: web/src/app/projects/view/view.component.ts (hunk 2 above)
Comment (eddiejaoude) [reply web/src/app/projects/view/view.component.ts]: 👍

File: web/src/app/projects/view/view.component.ts [hunk 5]
```diff
@@ -40,9 +40,7 @@ export class ViewProjectComponent implements OnInit {
     }
 
     ngOnInit(): void {
-        this.projectSubscription = this.projectService
-            .findOneById(this.project.uid)
-            .subscribe((project: ProjectModel) => {
+        this.projectSubscription = this.projectService.findOneById(this.project.uid).subscribe((project: ProjectModel) => {
```
Comment (eddiejaoude) [inline web/src/app/projects/view/view.component.ts]: sorry, I didn't meant the whole line, I just mean the return in the subscribe

```typescript
.subscribe((project: ProjectModel) => this.project = project)
```

File: web/src/resolvers/edit-project.resolver.ts [hunk 6]
```diff
@@ -10,9 +10,11 @@ import { ProjectService } from '../services/project.service';
...
 export class EditProjectResolver implements Resolve<boolean> {
 
-    constructor(private authService: AuthenticationService,
-                private projectService: ProjectService,
-                private router: Router) {
+    constructor(
+        private authService: AuthenticationService,
+        private projectService: ProjectService,
+        private router: Router
+        ) {
```
Comment (eddiejaoude) [inline web/src/resolvers/edit-project.resolver.ts]: I think this is more readable. Does the IDE not do this automatically?

```typescript
constructor(
   private authService: AuthenticationService,
   private projectService: ProjectService,
   private router: Router
) { }
```

File: web/src/app/projects/view/view.component.ts (hunk 5 above)
Comment (webkhushboo) [reply web/src/app/projects/view/view.component.ts]: Done !!

File: web/src/resolvers/edit-project.resolver.ts (hunk 6 above)
Comment (webkhushboo) [reply web/src/resolvers/edit-project.resolver.ts]: Yes Id does it automatically , I have updated it initially. Will take Id formatting going forward

File: web/src/app/projects/view/view.component.ts [hunk 7]
```diff
@@ -40,9 +40,9 @@ export class ViewProjectComponent implements OnInit {
     }
 
     ngOnInit(): void {
-        this.projectSubscription = this.projectService.findOneById(this.project.uid).subscribe((project: ProjectModel) => {
-                this.project = project;
-            });
+        this.projectSubscription = this.projectService
+            .findOneById(this.project.uid)
+            .subscribe((project: ProjectModel) => { this.project = project; });
```
Comment (eddiejaoude) [inline web/src/app/projects/view/view.component.ts]: the curly brackets are not needed 😄 

https://github.com/DashboardHub/PipelineDashboard/pull/1194#discussion_r279042504

File: web/src/resolvers/edit-project.resolver.ts (hunk 6 above)
Comment (eddiejaoude) [reply web/src/resolvers/edit-project.resolver.ts]: 👍

File: web/src/app/projects/view/view.component.ts (hunk 7 above)
Comment (webkhushboo) [reply web/src/app/projects/view/view.component.ts]: Point to be noted !! Fixed

Comment (eddiejaoude) [reply web/src/app/projects/view/view.component.ts]: 👍 🤓

File: web/src/app/projects/edit/edit.component.ts [hunk 8]
```diff
@@ -39,7 +42,9 @@ export class EditProjectComponent implements OnInit {
 
         this.projectSubscription = this.projectService
             .findOneById(this.uid)
-            .subscribe((project: ProjectModel) => this.projectForm.reset(project));
+            .subscribe((project: ProjectModel) => {
+                    this.projectForm.reset(project);
+            });
```
Comment (eddiejaoude) [inline web/src/app/projects/edit/edit.component.ts]: Same here, single line is possible

```typescript
.subscribe((project: ProjectModel) => this.projectForm.reset(project));
```

**Comment by eddiejaoude** [comment]
> Chore(style):Removed unneccessary semicolon

Its best to keep all the commit message lowercase as you were doing before
